public class JavaCaseProblem_marvin_malolot {

    
    public static void main(String[] args) {
        System.out.println("marvin malolot");
        System.out.println("student id 2024304015");
        System.out.println("===========================");
        System.out.println("Output: ");

    int num = 1000;
    int num2 = 2000;
    int sum = num + num2;

    
    System.out.println("The sum of " + num + " and " + num2 + " is: " + sum);
    }
}

